Transition SimplifyPointerBitcastPass to opaque pointers
google/clspv pull request #909
Opened 2022-08-12 10:35 UTC by omarahmed1111

# PR changes
* **Modify `SimplifyPointerBitcastPass::runOnBitcastFromGEP`**: This function should simplify cases when we bitcast a pointer that is generated from gep instruction. Before opaque pointers that case was valid as we could transform a pointer type to another pointer type like (i64* to i32*). After opaque pointer changes that case can't happen and will always be a trivial bitcast as we don't have any pointer type other than "ptr". Trivial bitcasts will be handled with `runOnTrivialBitcast`. So, we should delete this function after full transformation to opaque pointers.  
Example: `runOnTrivialBitcast` will delete the bitcast instruction. 
```
%gep = getelementptr i32, ptr %ptr, i32 0     
%cast = bitcast ptr %gep to ptr
```

* **Modify `SimplifyPointerBitcastPass::runOnGEPFromBitcastCstExpr`**: This function should simplify cases when we have gep instruction with its pointer operand as a bitcast constant expression. Which will have a similar trivial case as `SimplifyPointerBitcastPass::runOnBitcastFromGEP`. So, we should delete this function after full transformation to opaque pointers. 
Example:  
`%gep = getelementptr i32, ptr bitcast (ptr %ptr to ptr), i32 0`  
LLVM passes will transform it to `getelementptr i32, ptr %ptr, i32 0`

* **Add some trivial and simple bitcast test cases**

### Related issues
https://github.com/google/clspv/issues/816

**This contribution is being made by Codeplay on behalf of Samsung.**

2022-08-12 10:36 UTC, omarahmed1111 commented on test/PointerCasts/trivial_casts.ll
> +}
Not a trivial bitcast but thought adding it as a prove of concept for opaque pointer transformation. as `opaque_trivial_casts.ll` have its similar version but with opaque pointer (which will be trivial). It also should cover a case that is not currently tested for `runOnBitcastFromGEP` (this function should be deleted after full transformation anyway).

2022-08-12 18:50 UTC, alan-baker requested changes
Mostly there. I think the GEP from GEP case needs additional checking now in an opaque pointer world though. There might be an implicit pointer cast between them so I think we need a check that the result element type of the first GEP is the same as the source element type of the second GEP. I believe that also works with transparent pointers too. It would be good to make sure there is coverage of those cases for opaque pointers too in the tests.

2022-08-15 13:16 UTC, omarahmed1111 commented
> Mostly there. I think the GEP from GEP case needs additional checking now in an opaque pointer world though. There might be an implicit pointer cast between them so I think we need a check that the result element type of the first GEP is the same as the source element type of the second GEP. I believe that also works with transparent pointers too. It would be good to make sure there is coverage of those cases for opaque pointers too in the tests.

Fixed and added small simple tests for that.

2022-08-16 14:52 UTC, alan-baker approved these changes

2022-08-16 14:52 UTC, merged