Implement --use-native-builtins flag.
google/clspv pull request #911
Opened 2022-08-18 16:57 UTC by aarongreig

This allows avoiding builtin library implementations of specified builtin functions.

Also add a handful of tests for the new flag, builtins selected are all functions that we rely on libclc for, and that map directly to a glsl instruction.

This is the most generic version of the flag with the most validation, I had to shuffle stuff around to get the lookups working and it fails noisily if you pass it a builtin that we can't replace. I could revert some of the validation related changes if we restricted it to only functions we can map directly to a glsl extended instruction and it would still serve my purposes just fine, but I figured the maximum utility version was the best first proposal.

Based on discussion in #888 

This contribution is being made by Codeplay on behalf of Samsung.

2022-08-19 10:09 UTC, aarongreig commented
CI seems to have an issue finding the vulkan headers
```
/bin/clang-8.0.0/bin/clang++  -DCOMPILER_AVAILABLE -I../external/OpenCL-Headers -I/tmpfs/src/github/clspv/third_party/llvm/llvm/include -Iexternal/clspv/third_party/llvm/include -I/tmpfs/src/github/clspv/third_party/llvm/llvm/utils/unittest/googletest/include -I../tests/../src -I../external/SPIRV-Tools/include -I../external/SPIRV-Headers/include -I/tmpfs/src/github/clspv/include -Iexternal/clspv/include -I/tmpfs/src/github/clspv/third_party/llvm/llvm/utils/unittest/googlemock/include -fdiagnostics-color -g   -DCLSPV_ONLINE_COMPILER -std=gnu++14 -MD -MT tests/api/CMakeFiles/api_tests.dir/images.cpp.o -MF tests/api/CMakeFiles/api_tests.dir/images.cpp.o.d -o tests/api/CMakeFiles/api_tests.dir/images.cpp.o -c ../tests/api/images.cpp
In file included from ../tests/api/images.cpp:18:
In file included from ../tests/../src/utils.hpp:17:
../tests/../src/log.hpp:20:10: fatal error: 'vulkan/vulkan.h' file not found
#include <vulkan/vulkan.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

2022-08-19 10:14 UTC, rjodinchr commented
> CI seems to have an issue finding the vulkan headers
> 
> ```
> /bin/clang-8.0.0/bin/clang++  -DCOMPILER_AVAILABLE -I../external/OpenCL-Headers -I/tmpfs/src/github/clspv/third_party/llvm/llvm/include -Iexternal/clspv/third_party/llvm/include -I/tmpfs/src/github/clspv/third_party/llvm/llvm/utils/unittest/googletest/include -I../tests/../src -I../external/SPIRV-Tools/include -I../external/SPIRV-Headers/include -I/tmpfs/src/github/clspv/include -Iexternal/clspv/include -I/tmpfs/src/github/clspv/third_party/llvm/llvm/utils/unittest/googlemock/include -fdiagnostics-color -g   -DCLSPV_ONLINE_COMPILER -std=gnu++14 -MD -MT tests/api/CMakeFiles/api_tests.dir/images.cpp.o -MF tests/api/CMakeFiles/api_tests.dir/images.cpp.o.d -o tests/api/CMakeFiles/api_tests.dir/images.cpp.o -c ../tests/api/images.cpp
> In file included from ../tests/api/images.cpp:18:
> In file included from ../tests/../src/utils.hpp:17:
> ../tests/../src/log.hpp:20:10: fatal error: 'vulkan/vulkan.h' file not found
> #include <vulkan/vulkan.h>
>          ^~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
#898

2022-08-23 19:53 UTC, alan-baker requested changes
Looks good for the most part, but I'm not sure why the option parser is part of the public API.

2022-08-23 19:53 UTC, alan-baker commented on include/clspv/Option.h
> +struct BuiltinListParser
This seems unnecessary in the header. Can remove the command line header include too.

2022-08-24 16:35 UTC, aarongreig commented
thanks for the review

2022-08-24 21:40 UTC, alan-baker approved these changes

2022-08-24 21:40 UTC, merged