Reorder passes so long vector pod args get lowered to arrays.
google/clspv pull request #931
Opened 2022-09-29 14:13 UTC by aarongreig

This stops us hitting an assert that would otherwise happen when a long vector kernel arg didn't fit in regular push constant memory (or was forbidden from it by a flag like -no-16-bit-storage).

2022-09-29 14:41 UTC, rjodinchr requested changes

2022-09-29 14:43 UTC, rjodinchr commented on test/LongVectorLowering/cluster_pod_args_offsets.cl
> +// CHECK: OpMemberDecorate [[struct]] 5 Offset 80
See #906 and #907 to understand how alignment is managed in those 2 passes.

2022-09-29 15:15 UTC, aarongreig commented on test/LongVectorLowering/cluster_pod_args_offsets.cl
> +// CHECK: OpMemberDecorate [[struct]] 5 Offset 80
I was suspicious of this but couldn't figure what was up with it, back to the drawing board I go

2022-10-06 13:28 UTC, aarongreig commented
is there a way to trigger a CI retry? I think that would be the appropriate response to this failure:
```
/usr/bin/ld: out of memory allocating 1000 bytes after a total of 7914577920 bytes
```

2022-10-13 13:42 UTC, alan-baker commented
I'm getting through these PRs, but I was away for a couple weeks. Please bear with me.

2022-10-13 13:57 UTC, aarongreig commented
No worries!

2022-10-24 14:32 UTC, alan-baker approved these changes

2022-10-24 14:32 UTC, merged