Added command line option to specify CL3.0 feature macros
google/clspv pull request #941
Opened 2022-10-24 09:56 UTC by FMarno

This adds the ability to specify OpenCL3.0 feature macros that should be enabled by the clang frontend.

One thing I'm not sure about in this PR is the overlap of some options, specifically FP64 and ImageSupport. I think it would be best for the program to error out when one of these is disabled but the feature macro is enabled, but I'm not sure how CLSPV usually manages that.

This contribution is being made by Codeplay on behalf of Samsung.

2022-10-24 19:58 UTC, alan-baker commented
Take a look at ParseOptions in lib/Compiler.cpp to see how we handle incompatible options specifications.

I think longer term we may want to deprecate (and remove) some options if we want to specify feature macros.

2022-10-26 12:24 UTC, FMarno commented
Thanks @alan-baker, that worked well for me.

2022-10-27 13:12 UTC, FMarno commented
I think I've fixed the MSVC compile error, unfortunately I don't have a machine to test it on.

2022-10-27 18:29 UTC, alan-baker requested changes
Just nits.

2022-10-27 18:29 UTC, alan-baker commented on lib/Compiler.cpp
> +          enabled_feature_macros.end()) {
```suggestion
  if (!clspv::Option::FP64() &&
      enabled_feature_macros.count(clspv::FeatureMacro::__opencl_c_fp64)) {
```

2022-10-27 18:29 UTC, alan-baker commented on lib/Compiler.cpp
> +          enabled_feature_macros.end()) {
```suggestion
  if (!clspv::Option::ImageSupport() &&
      enabled_feature_macros.count(clspv::FeatureMacro::__opencl_c_images)) {
```

2022-10-28 18:13 UTC, alan-baker approved these changes

2022-10-28 18:14 UTC, merged