Better handling for opaque pointers in replace bitcasts
google/clspv pull request #978
Opened 2022-12-12 21:05 UTC by alan-baker

Contributes to #816

* Further generalizes the fix from #973 to only operate on a single implicit bitcast at a time instead of all bitcasts from the same source
  * properly handles both non-casts cases (previous PR) and when there are multiple different types of casts from the same source

2022-12-12 21:26 UTC, alan-baker commented
This fixes the roundTrip half CTS test.

2022-12-13 07:50 UTC, rjodinchr requested changes

2022-12-13 07:50 UTC, rjodinchr commented on lib/ReplacePointerBitcastPass.cpp
> +  errs() << M << "\n";
encapsulate in `LLVM_DEBUG`?

2022-12-13 07:51 UTC, rjodinchr commented
> This fixes the roundTrip half CTS test.

This test is passing in g3 as well as in chromeos. Do you mean it fixes it with the opaque pointers enabled?

2022-12-13 14:27 UTC, alan-baker commented
> > This fixes the roundTrip half CTS test.
> 
> This test is passing in g3 as well as in chromeos. Do you mean it fixes it with the opaque pointers enabled?

Yes, it is failing with opaque pointers on main.

2022-12-13 14:28 UTC, alan-baker commented on lib/ReplacePointerBitcastPass.cpp
> +  errs() << M << "\n";
I forgot to remove it.

2022-12-13 15:51 UTC, rjodinchr approved these changes

2022-12-13 17:07 UTC, merged